version: '3'

services:
    database:
        image: mysql:5.7
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/dump:/docker-entrypoint-initdb.d
            - ./docker/mysql/conf:/etc/mysql/conf.d
            - ./var/import:/var/lib/mysql-files
        ports:
            - 3308:3306
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - mysqlcsvreader

networks:
    mysqlcsvreader: